name: opennutritracker
description: Open-Source Calories & Activity Tracker

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.6.2+8

environment:
  sdk: '>=2.18.1 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  collection: ^1.17.0
  intl: ^0.18.0
  get_it: ^7.6.0
  provider: ^6.0.5
  http: ^1.1.0
  uuid: ^3.0.7
  json_annotation: ^4.8.0
  logging: ^1.1.1
  path_provider: ^2.0.14
  flutter_secure_storage: ^8.0.0
  cupertino_icons: ^1.0.5
  package_info_plus: ^4.0.2
  url_launcher: ^6.1.10
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3
  flutter_cache_manager: ^3.3.0
  envied: ^0.3.0+3

  flutter_bloc: ^8.1.2
  equatable: ^2.0.5

  percent_indicator: ^4.2.3
  horizontal_picker: ^1.2.0
  table_calendar: ^3.0.9
  introduction_screen: ^3.1.8
  auto_size_text: ^3.0.0

  mobile_scanner: ^3.2.0

  hive: ^2.2.3
  hive_flutter: ^1.1.0

  sentry_flutter: ^7.8.0

  supabase_flutter: ^1.10.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.13.1
  hive_generator: ^2.0.0
  envied_generator: ^0.3.0+3

flutter:

  uses-material-design: true

  assets:
    - assets/icon/ont_logo_square.png
    - assets/icon/ont_logo_square.svg
    - assets/icon/ont_logo_square_light.png
    - assets/icon/ont_banner_top.png
    - assets/icon/ont_banner_top_light.png

  fonts:
    - family: CustomIcons
      fonts:
      - asset: fonts/CustomIcons.ttf
    - family: Poppins
      fonts:
      - asset: fonts/Poppins-Black.ttf
      - asset: fonts/Poppins-BlackItalic.ttf
        style: italic
      - asset: fonts/Poppins-Bold.ttf
      - asset: fonts/Poppins-BoldItalic.ttf
        style: italic
      - asset: fonts/Poppins-ExtraBold.ttf
      - asset: fonts/Poppins-ExtraBoldItalic.ttf
        style: italic
      - asset: fonts/Poppins-ExtraLight.ttf
      - asset: fonts/Poppins-ExtraLightItalic.ttf
        style: italic
      - asset: fonts/Poppins-Italic.ttf
        style: italic
      - asset: fonts/Poppins-Light.ttf
      - asset: fonts/Poppins-LightItalic.ttf
        style: italic
      - asset: fonts/Poppins-Medium.ttf
      - asset: fonts/Poppins-MediumItalic.ttf
        style: italic
      - asset: fonts/Poppins-Regular.ttf
      - asset: fonts/Poppins-SemiBold.ttf
      - asset: fonts/Poppins-SemiBoldItalic.ttf
        style: italic
      - asset: fonts/Poppins-Thin.ttf
      - asset: fonts/Poppins-ThinItalic.ttf
        style: italic

flutter_intl:
  enabled: true

flutter_launcher_icons:
  android: true
  adaptive_icon_foreground: "assets/icon/ont_logo_square.png"
  adaptive_icon_background: "#ffffff"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/ont_logo_square.png"
  min_sdk_android: 21
