name: opennutritracker
description: Open-Source Calories & Activity Tracker

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.10.0+40

environment:
  sdk: '>=3.0.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  collection: ^1.19.0
  intl: ^0.19.0
  get_it: ^8.0.3
  provider: ^6.1.2
  http: ^1.2.2
  uuid: ^4.5.1
  json_annotation: ^4.9.0
  logging: ^1.3.0
  path_provider: ^2.1.5
  flutter_secure_storage: ^9.2.2
  cupertino_icons: ^1.0.8
  package_info_plus: ^8.1.2
  url_launcher: ^6.3.1
  flutter_svg: ^2.0.16
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  envied: ^1.0.0
  archive: 4.0.6
  file_picker: 10.1.2

  flutter_bloc: ^8.1.6
  equatable: ^2.0.7

  percent_indicator: ^4.2.4
  horizontal_picker: ^1.2.0
  table_calendar: ^3.1.3
  introduction_screen: ^3.1.14
  auto_size_text: ^3.0.0
  animated_flip_counter: ^0.3.4

  mobile_scanner: ^6.0.2

  hive: ^2.2.3
  hive_flutter: ^1.1.0

  sentry_flutter: ^8.11.2

  supabase_flutter: ^2.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.14
  json_serializable: ^6.7.1
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2
  hive_generator: ^2.0.1
  envied_generator: ^1.0.0
  mockito: ^5.4.5

flutter:

  uses-material-design: true

  assets:
    - assets/icon/ont_logo_square.png
    - assets/icon/ont_logo_square.svg
    - assets/icon/ont_logo_square_light.png
    - assets/icon/ont_banner_top.png
    - assets/icon/ont_banner_top_light.png

  fonts:
    - family: CustomIcons
      fonts:
      - asset: fonts/CustomIcons.ttf
    - family: Poppins
      fonts:
      - asset: fonts/Poppins-Black.ttf
      - asset: fonts/Poppins-BlackItalic.ttf
        style: italic
      - asset: fonts/Poppins-Bold.ttf
      - asset: fonts/Poppins-BoldItalic.ttf
        style: italic
      - asset: fonts/Poppins-ExtraBold.ttf
      - asset: fonts/Poppins-ExtraBoldItalic.ttf
        style: italic
      - asset: fonts/Poppins-ExtraLight.ttf
      - asset: fonts/Poppins-ExtraLightItalic.ttf
        style: italic
      - asset: fonts/Poppins-Italic.ttf
        style: italic
      - asset: fonts/Poppins-Light.ttf
      - asset: fonts/Poppins-LightItalic.ttf
        style: italic
      - asset: fonts/Poppins-Medium.ttf
      - asset: fonts/Poppins-MediumItalic.ttf
        style: italic
      - asset: fonts/Poppins-Regular.ttf
      - asset: fonts/Poppins-SemiBold.ttf
      - asset: fonts/Poppins-SemiBoldItalic.ttf
        style: italic
      - asset: fonts/Poppins-Thin.ttf
      - asset: fonts/Poppins-ThinItalic.ttf
        style: italic

flutter_intl:
  enabled: true

flutter_launcher_icons:
  android: true
  adaptive_icon_foreground: "assets/icon/ont_logo_square.png"
  adaptive_icon_background: "#ffffff"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/ont_logo_square.png"
  min_sdk_android: 21
